[package]
name = "lxp-bridge"
version = "0.1.0"
authors = ["Chris Elsworth <chris@cae.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "~1"
bytes = "~1"
crc16 = "~0.4"
env_logger = "~0.8"
futures = "~0.3"
log = "~0.4"
nom = "~6"
nom-derive = "~0.8"
num_enum = "~0.5"
rumqttc = "~0.5"
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
serde_yaml = "~0.8"
tokio = { version = "~1", features = [] }
tokio-util = { version = "~0.6", features = ["codec"] }
deadqueue = "~0.2"
structopt = "~0.3"
