inverters:
- enabled: true
  host: 127.0.0.1
  port: 30000
  serial: 1234567890
  datalog: 3000030000
- enabled: true
  host: 127.0.0.1
  port: 30001
  serial: 1234567891
  datalog: 3000130001

mqtt:
  enabled: true
  host: nas
  port: 1883
  username:
  password:
  # namespace: lxp

influx:
  enabled: true
  url: http://nas-vpn.cae.me.uk:8086
  username:
  password:
  database: lxp
  measurement: lxp
