inverters:
  - host: 127.0.0.1
    port: 30000
    serial: 1234567890
    datalog: AB12345670
  - host: 127.0.0.1
    port: 30001
    serial: 1234567891
    datalog: AB12345671


mqtt:
  host: nas
  port: 1883
  username:
  password:
  # namespace: lxp

influx:
  url: http://nas-vpn.cae.me.uk:8086
  username:
  password:
  database: lxp
  measurement: lxp
